"""empty message

Revision ID: 1b5478ffaf96
Revises: 182256d79165
Create Date: 2024-06-12 17:04:30.437283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5478ffaf96'
down_revision = '182256d79165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_constraint('albums_status_key', type_='unique')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('albums_status_key', ['status'])

    # ### end Alembic commands ###
