"""empty message

Revision ID: d1d18d10ec8a
Revises: c9a1156f8c31
Create Date: 2024-06-17 18:53:48.561789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d18d10ec8a'
down_revision = 'c9a1156f8c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint('rooms_price_key', type_='unique')
        batch_op.drop_constraint('rooms_square_meters_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_unique_constraint('rooms_square_meters_key', ['square_meters'])
        batch_op.create_unique_constraint('rooms_price_key', ['price'])

    # ### end Alembic commands ###
